import Head from 'next/head'
import { SSRProvider } from 'react-bootstrap'
import CookiesProvider from 'react-cookie/cjs/CookiesProvider'
import SignupPage from './sign-up'


export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <CookiesProvider>
        <SSRProvider>
          <SignupPage />
        </SSRProvider>
      </CookiesProvider>


    </>
  )
}
