import Head from 'next/head'
import ChannelPage from './channel/:[channel_id]'
import CreateChannelPage from './channel/create'
import LoginForm from './login'
import MessagePage from './message/:[user_id]'
import ProfilePage from './profile'
import SignupPage from './sign-up'


export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <SignupPage/>


    </>
  )
}
